### ISSUE TITLE
ERROR: ModuleNotFoundError: No module named 'quadai'

### ISSUE THREAD

**Issue by rouhUAV** [AlexandreSajus/2D-Quadcopter-AI#2]
Hi!
Such a cute code.
I have import your repository to my pycharm IDE, it gives me this error:
"ModuleNotFoundError: No module named 'quadai'"

have I missed something?

**Comment by AlexandreSajus** [comment]
Hello, and thank you!

I assume you are trying to edit the project's code within Pycharm. If Python can't find the quadai module, it probably means that the current working directory is incorrect. In Pycharm, open the Quadcopter-AI-main folder containing assets, DQN, and Human... to set it as the current working directory. This should solve the issue. If it doesn't, don't hesitate to ask me for help with a bit more context.

If you are trying to run the project, please follow the instructions in the README.

**Comment by rouhUAV** [comment]
Thank you Alex for your kind response.
I agree that the problem is basically about the project structure in PyCharm, but I have tried some solutions on it, none of them lead me to success.
I see that, those folders you mentioned are under " Quadcopter-AI-main\src" so I changed the  working directories to the src too. but it did not help...

![Annotation 2023-06-03 122753](https://github.com/AlexandreSajus/Quadcopter-AI/assets/108422149/17b3a80f-19fb-41fd-92b3-c924f3f3171d)

**Comment by AlexandreSajus** [comment]
I see... I tried reproducing the issue but it doesn't appear on a fresh venv in Python 3.10.6.

I can suggest a few possibles fixes:
- From Quadcopter-AI as CWD, you can run
  ```python
  pip install -e .
  ```

  ![image](https://github.com/AlexandreSajus/Quadcopter-AI/assets/62465003/7babeb89-9c37-48e7-b54e-90ad19402259)
  
  
    This should install quadai using setup.py as an editable package
  
  ![image](https://github.com/AlexandreSajus/Quadcopter-AI/assets/62465003/86e0155e-9ee8-4046-bcdd-b5b9e081ddce)


- Another potential fix would be setting CWD to src/quadai

Let me know if this works

**Comment by rouhUAV** [comment]
thank you :) , it did work:
`pip install -e .`
Why does it need a separate installation beside compiling?

**Comment by AlexandreSajus** [comment]
As I understand it: `pip install -e .` is to install your package as editable so you can edit it and run it in your environment from whatever CWD. I did not think it was necessary for development but apparently, it is.
