### ISSUE TITLE
Compatibility Issues in train_SAC.py

### ISSUE THREAD

**Issue by AlbertoGigantelliGabriele** [AlexandreSajus/2D-Quadcopter-AI#4]
👋

I'm experiencing library compatibility issues when attempting to run train_SAC.py. 

Specifically, the problem(s) arises with the following libraries: gym, gymnasium, wandb, stable-baselines3.

AssertionError: The algorithm only supports (<class 'gymnasium.spaces.box.Box'>,) as action spaces but Box(-1.0, 1.0, (2,), float32) was provided.

I've tried downgrading to older versions of some of these libraries, but the incompatibility issues persist. Maybe you should specify versions in requirements.txt ?

**Comment by AlexandreSajus** [comment]
Hey! Thanks for bringing that to my attention! I just pushed a new requirements.txt file containing working versions for packages (at least working on my Python 3.8.10).

I should have specified these earlier. Both stable-baselines3 and gym have moved on to a newer version of a gym called gymnasium, which made my gym environment obsolete. I could not find a virtual environment on my computer that made the project work, so I just looked at the date of my last working commit, took releases for both packages before that date, and tested them.

Let me know if it works so I can close the issue.

**Comment by AlbertoGigantelliGabriele** [comment]
The training seems to be starting properly. The only hitch is found in gym==0.21.0 "extras_require" which in this version has an error in the setup.py file specifying the "other" version: ["lz4>=3.1.0", "opencv-python >=3 ."], so I recommend manually fixing the error and installing it manually.
